      const translations = {
        ar: {
          gameTitle: "مافيا الفرسان",
          kingdomTitle: "مملكة أبو الجعافير العظيمة",
          homeDescription:
            "تجربة لعبة المافيا الكلاسيكية بحلة فروسية العصور الوسطى. مرر الهاتف سراً بين اللاعبين لتقوم المملكة بحساب القتل، التحقيقات، والتصويت تلقائياً بدون الحاجة لحَكَم!",
          newGame: "بدء مغامرة جديدة",
          encyclopedia: "📖 موسوعة الأدوار والقوانين",
          statistics: "📊 جدول النقاط والأحصائيات",
          presets: "⚙️ إعدادات التشكيلات السريعة",
          back: "رجوع",
          seatingNext: "ترتيب الجلسة ثم توزيع الأدوار 🎴",
          seatingTitle: "ترتيب الجلسة",
          seatingSubtitle: "اجلسوا بشكل دائري بهالترتيب عشان يسهل تمرير الجوال",
          start: "ابدأ",
          passTo: "مرر الجوال في سرية تامة إلى",
          secretDoc: "⚜️ وثيقة سرية ⚜️",
          clickToReveal: "اضغط للكشف عن هويتك",
          tapToHide: "المس الكرت لإخفائه مجدداً",
          passPhone: "حفظ وإخفاء الدور وتمرير الجوال 🔒",
          exitConfirmTitle: "⚠️ هل أنت متأكد من الخروج من اللعبة؟",
          exitConfirmNote:
            "⚠️ ملاحظة: لن يتم إحتساب هذه الجولة (لن تظهر في الأحصائيات).",
          btnExit: "🚪 خروج",
          btnContinue: "▶️ إكمال اللعب",
          hiddenDocument: "تم إخفاء الوثيقة السرية",
          passToPlayer: "مرر الجوال في سرية تامة إلى: {name}",
          confirmPlayer: "أنا {name} - جاهز لكشف دوري",
          playerRole: "الفارس: {name}",
          passNight: "حل الليل على المملكة... مرر الجوال سراً إلى:",
          openMission: "فتح المهمة السرية 🗝️",
          discussion: "بدء جلسة النقاش والمحاكمة ⚖️",
          vote: "الانتقال إلى منصة التصويت 🗳️",
          confirmVote: "تأكيد التصويت ⚔️",
          close: "إغلاق",
          skip: "تخطي / امتناع",
          statsTitle: "📊 سجل النقاط والإحصائيات",
          player: "اللاعب",
          points: "النقاط",
          kills: "عدد القتلات",
          badges: "الألقاب",
          wins: "الفوز",
          losses: "الخسائر",
          rolesWon: "الأدوار الفائز بها",
          resetStats: "🗑️ تصفير جميع النقاط والبيانات",
          setupPlayers: "1. أسماء الفرسان",
          setupRoles: "2. اختيار الأدوار",
          setupRules: "3. القواعد الملكية",
          playerHeading: "👥 تسجيل اللاعبين",
          add: "إضافة",
          roleSetup: "🎭 تخصيص الأدوار",
          rulesHeading: "⚖️ خيارات وقواعد المملكة",
          epicSubtitle: " • بدون مدير (أوفلاين بالكامل)",
          kingdomWord: "في المملكة",
          knightsTeam: "فريق الفرسان",
          mafiaTeam: "فريق المافيا",
          neutralTeam: "محايد منفرد",
          revealRoleRule: "كشف دور المطرود",
          revealRoleNote: "إعلان هوية اللاعب فور إقصائه نهاراً",
          showVotesRule: "إظهار تفاصيل الأصوات",
          showVotesNote: "كشف من صوت ضد من بعد انتهاء النهار",
          discussionTimerRule: "مدة مؤقت النقاش النهاري",
          minutes: "دقائق",
          confirmAction: "تأكيد وإنهاء الدور 🌙",
          skipActionNote: "(لا تختار أحداً لتخطي دورك)",
          mafiaPrompt:
            "أيها المافيا، اختر الهدف المراد اغتياله وتصفيته الليلة:",
          partner: "🕵️ شريكك في المافيا:",
          setupRolePrompt: "اختر الأدوار لتطابق تماماً عدد اللاعبين المسجلين.",
          roleUnit: "دور",
          maxPlayers: "الحد الأقصى للمملكة 16 فارساً!",
          duplicatePlayer: "هذا الاسم مسجل بالفعل!",
          quickFillSuccess: "تمت إضافة 5 لاعبين افتراضيين وتشكيل متوازن!",
          minPlayers: "يجب تسجيل 5 لاعبين على الأقل لبدء اللعبة!",
          roleMismatch:
            "مجموع الأدوار ({roles}) لا يطابق عدد اللاعبين ({players})!",
          scoringGuide: "📜 شرح آلية النقاط",
          scoringTitle: "📜 دليل توزيع النقاط والفوزات",
          baseWinTitle: "🏆 الفوز الأساسي",
          baseWinDesc: "تُضاف نقاط الفوز حسب الفريق والدور الفائز، مع +1 لسجل الفوز.",
          knightsTitle: "🛡️ فريق الفرسان (الصالحين)",
          knightsKills:
            "• فوز الجولة: +10 نقاط لكل لاعب حي من الفرسان\n• قتل مافيا عادي: +5 نقاط\n• قتل زعيم المافيا (العرّاب): +15 نقطة\n• التصويت لإقصاء القاتل المتسلسل (السفاح): +10 نقاط لكل من صوت عليه\n• تضحية الحارس الشخصي: +15 نقطة\n• حماية ناجحة للطبيب: +25 نقطة عند إنقاذ شخص تعرض للهجوم فعلياً\n• تحقيق ناجح للمحقق: +15 نقطة عن كل عضو مافيا يتم كشفه\n• طلقة صياد الوحوش الأخيرة: +10 نقاط عند إصابة مافيا أو سفاح\n• قيادة التصويت الناجحة للعقيد الحاكم: +15 نقطة",
          mafiaTitle: "🗡️ فريق المافيا",
          mafiaKills:
            "• فوز الجولة: +20 نقطة لكل عضو مافيا مشارك\n• قتل القناص أو الساحرة: +10 نقاط\n• قتل المحقق الإمبراطوري: +10 نقاط\n• قتل طبيب الطاعون: +10 نقاط\n• قتل القاتل المتسلسل (السفاح): +10 نقاط\n• قتل الجاسوس: +15 نقطة\n• قتل مواطن عادي / كيوبيد / حارس: +5 نقاط",
          neutralTitle: "🎭 الأدوار المحايدة",
          neutralRules:
            "• فوز المهرج (إعدامه بالتصويت): +50 نقطة\n• فوز السفاح (البقاء حياً وتصفية الجميع): +70 نقطة\n• تفجير الانتحاري المتمرد وأخذ مصوت معه: +10 نقاط\n• بقاء مربوطين كيوبيد حتى النهاية: +10 نقاط\n• فشل كيوبيد (موت الثنائي المربوط): -5 نقاط",
          penaltiesTitle: "⚠️ خصومات وعقوبات (مسموح النقاط بالسالب)",
          penaltiesDesc:
            "• التصويت على الجوكر: -5 نقاط (سواء فاز أو لا)\n• التصويت على المجنون: -5 نقاط\n• النيران الصديقة: -10 نقاط\n• التصويت على الانتحاري: -5 نقاط\n• التصويت لإعدام بريء من الفرسان: -5 نقاط",
          scoring_bodyguard_sacrifice:
            "• تضحية الحارس الشخصي: +15 نقطة (عند الموت لحماية هدفه)",
          scoring_cupid_failure: "• فشل كيوبيد (موت الثنائي المربوط): -5 نقاط",
          scoring_friendly_fire:
            "• النيران الصديقة (قتل صديق بالخطأ): -10 نقاط",
          scoring_doctor_heal: "• حماية ناجحة للطبيب: +25 نقطة عند إنقاذ شخص تعرض للهجوم فعلياً",
          scoring_hunter_shot:
            "• طلقة صياد الوحوش الأخيرة (إصابة مافيا/سفاح): +10 نقاط",
          scoring_colonel_lead:
            "• قيادة التصويت الناجحة للعقيد الحاكم: +15 نقطة",
          scoring_mafia_standard_kill:
            "• قتل مواطن عادي / كيوبيد / حارس: +5 نقاط",
          scoring_joker_win: "• فوز المهرج (إعدامه بالتصويت): +50 نقطة",
          scoring_bomber_detonate: "• تفجير الانتحاري المتمرد: +10 نقاط",
          scoring_cupid_survival: "• بقاء مربوطين كيوبيد حتى النهاية: +10 نقاط",
          scoring_bomber_penalty: "• التصويت على الانتحاري: -5 نقاط",
          scoring_innocent_penalty: "• التصويت لإعدام بريء من الفرسان: -5 نقاط",
          playerRange: "🛡️ 6 إلى 16 لاعب",
          offlineMode: "⚡ 100% أوفلاين",
          roleCount: "🎭 16 دوراً ملكياً",
          nextNight: "متابعة حلول الليل التالي 🌙",
          sampleNames: "أسماء تجريبية",
          playerPlaceholder: "اسم الفارس / اللاعب...",
          roleSetupNote: "اختر الأدوار لتطابق تماماً عدد اللاعبين المسجلين.",
          presetTitle: "⚡ التشكيلات المتوازنة الجاهزة",
          preset6: "🛡️ تشكيلة 6 لاعبين (مبتدئ)",
          preset8: "⚔️ تشكيلة 8 لاعبين (كلاسيكية متوازنة)",
          preset10: "👑 تشكيلة 10 لاعبين (ملحمية)",
          preset12: "🔥 تشكيلة 12 لاعباً (فوضى وظلال)",
          cancel: "إلغاء",
          encyclopediaTitle: "📖 موسوعة أدوار العصور الوسطى",
          conflictEnd: "انتهاء الصراع الملكي",
          rolesRecord: "سجل هويات جميع اللاعبين:",
          restartSame: "إعادة اللعب بنفس التشكيلة ⚔️",
          home: "العودة للقائمة الرئيسية 🏰",
          specialConfirm: "تنفيذ الانتقام 🏹",
          specialDefaultTitle: "انتقام الصياد!",
          specialDefaultDesc:
            "لقد سقط الصياد صريعاً، وله الحق في إطلاق رصاصته الأخيرة على أي لاعب!",
          investigationTitle: "نتيجة التحقيق الإمبراطوري",
          inspectedIdentity: "هوية الفارس المفحوص",
          investigationStatus: "نتيجة التقصي",
          investigationContinue: "فهمت / إنهاء الدور ✓",
          playerRole: "الفارس: {name}",
          votePrompt: "أيها الفارس {name}، اختر من تتهمه بالخيانة:",
          targetPrefix: "⚔️ استهداف: ",
          protectPrefix: "🛡️ حماية: ",
          doctorSelfHealUsed: "تم استنفاد الحماية الذاتية",
          doctorSelfHealNote: "*(يمكنك علاج نفسك مرة واحدة فقط طوال اللعبة وقد استخدمتها سابقاً)*",
          mafiaPartners: "شركاؤك في المافيا: {names}",
          godfatherMafia: "أفراد المافيا تحت إمرتك: {names}",
          soloMafia: "أنت المافيا الوحيد في هذه اللعبة",
          passVotingPhone: "مرر الجوال في سرية تامة إلى الفارس: {name}",
          readyToVote: "أنا {name} - جاهز للتصويت",
          investigatePrefix: "🔍 اختبار: ",
          slasherPrompt: "أيها السفاح، اختر ضحيتك المستقلة لهذه الليلة:",
          bodyguardPrompt:
            "اختر فارساً لحراسته بحياتك (إذا استُهدف ستموت بدلاً عنه):",
          doctorPrompt:
            "اختر فارساً لحمايته وإنقاذه الليلة من الموت (يمكنك حماية نفسك):",
          investigatorPrompt:
            "اختر فارساً للتحقيق السري في هويته واكتشاف ولائه:",
          spyReveal: "قدرتك الاستخباراتية تكشف:",
          mafiaMove: "المافيا تتحرك لاغتيال: [{name}]",
          noMafiaMove: "لم يتم رصد أي تحرك للمافيا بعد.",
          cupidPrompt:
            "الليلة الأولى فقط: اختر قلبين لربطهما كمربوطين (إذا مات أحدهما مات الآخر):",
          chooseTwo: "اختر لاعبين اثنين:",
          cupidDone:
            "لقد قمت بربط المربوطين في الليلة الأولى ولا توجد إجراءات إضافية الليلة.",
          witchPrompt: "أيتها الساحرة، يمكنك استخدام جرعاتك الخاصة:",
          mafiaVictim: "ضحية المافيا الليلة:",
          noVictim: "لا يوجد",
          healVictim: "إنقاذ الضحية بجرعة الشفاء ({status})",
          witchHealSection: "قسم العلاج - جرعة الشفاء ({status})",
          witchPoisonSection: "قسم التسميم - جرعة السم القاتلة ({status})",
          witchAvailable: "متاحة",
          witchUsed: "تم استخدامها",
          available: "متاحة",
          used: "مستهلكة",
          poisonPrompt: "جرعة السم القاتلة ({status}):",
          poisonPrefix: "🧪 تسميم: ",
          sniperPrompt:
            "لديك رصاصة واحدة طوال المعركة. هل ترغب في قنص أحد الليلة؟",
          sniperSpent: "لقد استهلكت رصاصتك الملكية بالفعل.",
          sniperPrefix: "🎯 قنص: ",
          citizenPrompt:
            "أيها المواطن الصالح، تمويه الذئاب يتطلب بقاءك هنا ثوانٍ معدودة. اضغط على أي اسم لتشويش من يراقبك:",
          camouflagePrefix: "🛡️ تمويه: ",
          mafiaInvestigation: "عضو مافيا خائن! 🗡️",
          townInvestigation: "فارس شريف وبريء 🛡️",
          serialKillerInvestigation: "⚠️ هذا الفارس هو (السفاح) - خطر محايد!",
          jesterInvestigation: "🃏 هذا الفارس هو (المهرج) - محايد!",
          mafiaTeamInvestigation: "🗡️ هذا الفارس خائن! ( ينتمي لفريق المافيا )",
          innocentInvestigation: "🛡️ هذا الفارس بريء! ( ينتمي للفرسان )",
          abstainPrompt: "اختر هدفاً أو اضغط تخطي / امتناع.",
          voteAgainst: "صوت ضد",
          doubleWeight: "(وزن مضاعف)",
          skipVoteTitle: "📜 قرر المجلس التخطي وعدم إعدام أي فارس اليوم.",
          skipVoteDesc:
            "كانت أصوات التخطي مساوية أو أعلى من أصوات أكثر مشتبه به حصولاً على الأصوات. ستبدأ الليلة التالية الآن.",
          skipVoteContinue: "الانتقال إلى الليل 🌙",
          tieTitle: "تعادل في أصوات المجلس ⚖️",
          tieDesc:
            "انقسم الفرسان في آرائهم بالتساوي، ولم يحصل أي مشتبه به على أغلبية حاسمة؛ رُفعت الجلسة دون إعدام أحد اليوم.",
          jesterWin:
            "انتصر المهرج [{name}]! لقد نجح في خداعكم جميعاً وجعل المجلس يصوت على إعدامه.",
          idiotTitle: "عفو ملكي عن المجنون! 🥴",
          idiotDesc:
            "صوت المجلس لإعدام [{name}]، لكنه أظهر بلاهته وجنونه! تم العفو عنه مع تجريده من حق التصويت مستقبلاً.",
          executionTitle: "تم تنفيذ حكم الإعدام بحق: {name} ⚔️",
          executionDesc:
            "سقط [{name}] على يد الجلاد بعد نيله أعلى نسبة أصوات من مجلس الفرسان.",
          loverDeath: "💔 مات جحشه [{name}] فوراً كمداً وحسرة!",
          hunterTitle: "🦅 رصاصة الصياد الأخيرة!",
          hunterDesc:
            "أيها الصياد [{name}]، قبل أن تلفظ أنفاسك الأخيرة، اختر فارساً لتصفيته معك:",
          hunterToast: "أطلق الصياد سهمه وأردى [{name}] قتيلاً!",
          kamikazeTitle: "💣 انفجار الانتحاري المتمرد!",
          kamikazeDesc:
            "لقد أعدمتم الانتحاري [{name}]! اختر أحد الفرسان ليصطيشحطهه معه إلى القبر:",
          kamikazeToast: "فجر الانتحاري نفسه وقضى على [{name}]!",
          targetRequired: "يرجى اختيار هدف للانتقام!",
          loverMorning:
            "💔 لم يتحمل [{survivor}] فراق جحشه [{dead}] فمات حسرة وحزناً.",
          timerEnded: "انتهى وقت المشاورة! حان وقت التصويت.",
          executionRole: "الهوية الحقيقية للمقصى:",
          voteDetails: "تفاصيل سجل الأصوات:",
          noStats: "لا توجد إحصائيات محفوظة حتى الآن.",
          resetConfirm: "هل أنت متأكد من تصفير جميع النقاط والبيانات؟",
          resetSuccess: "تم تصفير جميع النقاط والبيانات بنجاح.",
          alive: "حي",
          dead: "ميت",
          loverLabel: "(مربوط)",
          bodyguardDeath:
            "⚔️ استُشهد الحارس الشخصي [{name}] بشجاعة مفتدياً الشخص الذي كان يحرسه.",
          mafiaDeath:
            "🗡️ عُثر على الفارس [{name}] مقتولاً في غرفته بعد غارة غادرة من المافيا.",
          savedByProtection:
            "✨ بفضل العناية والطب، نجا أحد الفرسان الليلة من موت محقق بإعجوبة!",
          slasherDeath:
            "🪓 سقط الفارس [{name}] ضحية لجريمة بشعة نفذها السفاح المتسلسل.",
          sniperDeath:
            "🏹 اخترق سهم القناص الملكي صدر الفارس [{name}] وأرداه قتيلاً.",
          witchDeath:
            "🧪 فارق الفارس [{name}] الحياة بعد تجرعه سماً مجهول المصدر.",
          townVictoryTitle: "⚔️ انتصار فرسان المملكة الشرفاء! 🛡️",
          mafiaVictoryTitle: "🗡️ انتصار فرسان المافيا الخونة! 💀",
          jesterVictoryTitle: "🃏 انتصار المهرج العبقري!",
          slasherVictoryTitle: "🪓 انتصار السفاح المنفرد!",
          loversVictoryTitle: "🪢 انتصارالمربوطين!",
          loversVictoryDesc:
            "انتصار المربوطين! صمد المربوطان حتى النهاية وتغلبا على مؤامرات المملكة.",
          slasherVictoryDesc:
            "انتصار السفاح المنفرد! تمكن من تصفية الجميع والوقوف بمفرده فوق الركام.",
          mafiaVictoryDesc:
            "انتصار المافيا وفرسان الظلام! سيطرت المافيا بالكامل على المملكة وأخضعت الجميع.",
          townVictoryDesc:
            "انتصار الفرسان والشرفاء! تم تطهير المملكة من كل الخونة والمجرمين وعاد الأمان.",
          roleStatus: "{name} {lover}{icon} {role} ({status})",
          livingKnights: "🛡️ الفرسان الأحياء في المجلس",
          royalBulletin: "📜 وثيقة الصباح الملكية 📜",
          dayInKingdom: "اليوم رقم",
          quietNight:
            "🕊️ ليلة هادئة ومباركة! استيقظت المملكة دون أي وفيات بين الفرسان.",
          publicDiscussion: "⏳ جلسة المشاورة العلنية",
          daylightActive: "النهار مفتوح",
          pause: "إيقاف مؤقت ⏸️",
          resume: "استئناف ▶️",
          reset: "إعادة ضبط 🔄",
          addThirty: "+30 ثانية ⏱️",
          discussionNote:
            "تناقشوا واتهموا المشتبه بهم قبل بدء التصويت على الإقصاء بالمقصلة!",
          royalVote: "🗳️ تصويت الإقصاء الملكي",
          knightVote: "صوت الفارس",
          accuseExecute: "⚖️ اتهام وإعدام:",
          skip: "تخطي / امتناع",
          tieMessage:
            "⚖️ تعادل في الأصوات! سيتم إعادة جولة التصويت بين المشتبه بهم فقط.",
          roles: {
            mafia: [
              "المافيا (الفرسان الخونة)",
              "يستيقظ أفراد المافيا كل ليلة لاختيار ضحية واحدة وتصفيتها بصمت.",
            ],
            citizen: [
              "المواطن الشريف",
              "لا يملك قدرات ليلية خاصة. سلاحه هو النقاش، قوة الملاحظة، والتصويت النهاري.",
            ],
            doctor: [
              "طبيب الطاعون",
              "يختار لاعباً كل ليلة ليحميه ويشفيه من محاولة اغتيال المافيا أو السفاح.",
            ],
            investigator: [
              "المحقق الإمبراطوري",
              "يتحقق من هوية لاعب واحد كل ليلة ليكتشف إن كان ينتمي للمافيا أم بريء.",
            ],
            sniper: [
              "القناص الملكي",
              "يمتلك سهماً واحداً طوال اللعبة يمكنه إطلاقه ليلاً على أي مشتبه به.",
            ],
            godfather: [
              "العراب (سيد الظلال)",
              "زعيم المافيا. إذا فحصه المحقق ليلاً، تظهر نتيجته كبريء للتمويه.",
            ],
            slasher: [
              "السفاح المنفرد",
              "قاتل متسلسل مستقل يقتل لاعباً كل ليلة ويسعى للبقاء وحيداً.",
            ],
            spy: [
              "الجاسوس الملكي",
              "يتجسس ليلاً لمعرفة من استهدفته المافيا دون كشف أسمائهم.",
            ],
            jester: [
              "المهرج (الجوكر)",
              "هدفه استفزاز الجميع وخداعهم للتصويت على إعدامه ليفوز فوراً!",
            ],
            colonel: [
              "العقيد الحاكم",
              "فارس نبيل صوته يعادل صوتين أثناء التصويت النهاري.",
            ],
            kamikaze: [
              "الانتحاري المتمرد",
              "إذا أُعدم نهاراً يفجر نفسه ويأخذ أحد المصوتين معه!",
            ],
            witch: [
              "الساحرة الكيميائية",
              "تمتلك جرعة إحياء وجرعة سم، مرة واحدة لكل جرعة.",
            ],
            bodyguard: [
              "الحارس الشخصي",
              "يحرس لاعباً كل ليلة ويضحي بنفسه إذا استُهدف ذلك اللاعب.",
            ],
            idiot: [
              "المجنون الأبله",
              "إذا صوّت المجلس لإعدامه يُعفى عنه ويفقد حق التصويت.",
            ],
            hunter: [
              "صياد الوحوش",
              "عند موته يطلق طلقته الأخيرة على لاعب يختاره.",
            ],
            cupid: [
              "كيوبيد (رسول المربوطين)",
              "في الليلة الأولى يربط جحشين؛ إذا مات أحدهما مات الآخر.",
            ],
          },
        },
        en: {
          gameTitle: "Mafia - Knights Edition",
          kingdomTitle: "The Great Kingdom of Abu Al-Jaafair",
          homeDescription:
            "A classic Mafia game in a medieval knightly setting. Pass the phone secretly while the kingdom manages kills, investigations, and voting without a moderator!",
          newGame: "Start New Adventure",
          encyclopedia: "📖 Roles & Rules Encyclopedia",
          statistics: "📊 Points & Statistics",
          presets: "⚙️ Quick Presets",
          back: "Back",
          seatingNext: "Arrange Seating & Deal Roles 🎴",
          seatingTitle: "Seating Arrangement",
          seatingSubtitle:
            "Sit in a circle in this order to make passing the phone easier",
          start: "Start",
          passTo: "Secretly pass the phone to",
          secretDoc: "⚜️ Classified Document ⚜️",
          clickToReveal: "Tap to reveal your identity",
          tapToHide: "Tap the card to hide it again",
          passPhone: "Save & Hide Role (Pass Phone) 🔒",
          exitConfirmTitle: "⚠️ Are you sure you want to exit the game?",
          exitConfirmNote:
            "⚠️ Note: This round will not be counted or appear in statistics.",
          btnExit: "🚪 Exit Game",
          btnContinue: "▶️ Continue Playing",
          hiddenDocument: "Secret Document Hidden",
          passToPlayer: "Pass the phone discreetly to: {name}",
          confirmPlayer: "I am {name} - ready to reveal my role",
          playerRole: "Player: {name}",
          passNight:
            "Night falls upon the Kingdom... Pass the phone secretly to:",
          openMission: "Open Secret Mission 🗝️",
          discussion: "Start Discussion & Trial ⚖️",
          vote: "Proceed to Voting Platform 🗳️",
          confirmVote: "Confirm Vote ⚔️",
          close: "Close",
          skip: "Skip / Abstain",
          statsTitle: "📊 Points & Leaderboard Record",
          player: "Player",
          points: "Points",
          kills: "Kills",
          badges: "Badges",
          wins: "Wins",
          losses: "Losses",
          rolesWon: "Roles Won",
          resetStats: "🗑️ Reset All Statistics",
          setupPlayers: "1. Knight Names",
          setupRoles: "2. Choose Roles",
          setupRules: "3. Kingdom Rules",
          playerHeading: "👥 Register Players",
          add: "Add",
          roleSetup: "🎭 Customize Roles",
          rulesHeading: "⚖️ Kingdom Rules",
          epicSubtitle: "Epic Edition • Moderator-Free (Fully Offline)",
          kingdomWord: "in the Kingdom",
          knightsTeam: "Knights Team",
          mafiaTeam: "Mafia Team",
          neutralTeam: "Independent Neutral",
          revealRoleRule: "Reveal Eliminated Role",
          revealRoleNote:
            "Announce player's identity immediately upon daytime elimination",
          showVotesRule: "Show Vote Breakdown",
          showVotesNote: "Reveal who voted against whom after daytime voting",
          discussionTimerRule: "Daytime Discussion Timer",
          minutes: "Minutes",
          confirmAction: "Confirm Action 🌙",
          skipActionNote: "(Select no one to skip your turn)",
          mafiaPrompt: "Mafia, choose the player to eliminate tonight:",
          partner: "🕵️ Your Mafia Teammate:",
          setupRolePrompt:
            "Select roles to match the exact number of registered players.",
          roleUnit: "Roles",
          maxPlayers: "The kingdom can have at most 16 knights!",
          duplicatePlayer: "That name is already registered!",
          quickFillSuccess: "Added 5 sample players with a balanced setup!",
          minPlayers: "At least 5 players are required to start!",
          roleMismatch:
            "The role total ({roles}) does not match the player count ({players})!",
          scoringGuide: "📜 Scoring Guide",
          scoringTitle: "📜 Scoring & Wins Guide",
          baseWinTitle: "🏆 Base Victory",
          baseWinDesc: "Victory points depend on the winning team and role, plus +1 to total Wins.",
          knightsTitle: "🛡️ Knights Team (Good Roles)",
          knightsKills:
            "• Round victory: +10 Pts for each living Knights player\n• Kill Regular Mafia: +5 Pts\n• Kill Godfather (Mafia Leader): +15 Pts\n• Vote Out Serial Killer: +10 Pts for each player who voted for them\n• Bodyguard Sacrifice: +15 Pts\n• Successful Doctor Protection: +25 Pts when saving an actually attacked player\n• Successful Investigator Reveal: +15 Pts for each Mafia member exposed\n• Monster Hunter Dying Shot: +10 Pts when hitting Mafia or the Serial Killer\n• Colonel Successful Vote Leadership: +15 Pts",
          mafiaTitle: "🗡️ Mafia Team",
          mafiaKills:
            "• Round victory: +20 Pts for each participating Mafia member\n• Kill Sniper or Witch: +10 Pts\n• Kill Investigator: +10 Pts\n• Kill Doctor: +10 Pts\n• Kill Serial Killer: +10 Pts\n• Kill Spy: +15 Pts\n• Kill Standard Citizen / Cupid / Guard: +5 Pts",
          neutralTitle: "🎭 Neutral Roles",
          neutralRules:
            "• Jester victory (executed by vote): +50 Pts\n• Slasher victory (surviving after eliminating everyone): +70 Pts\n• Rebel Bomber Detonation taking a voter: +10 Pts\n• Cupid Lovers Surviving: +10 Pts\n• Cupid Failure (both lovers die): -5 Pts",
          penaltiesTitle: "⚠️ Deductions & Penalties (Negative Scores Allowed)",
          penaltiesDesc:
            "• Voting for Joker: -5 Pts (whether revealed/eliminated or not)\n• Voting for Madman: -5 Pts\n• Friendly Fire: -10 Pts\n• Vote Against Rebel Bomber: -5 Pts\n• Vote to Execute Innocent Knight: -5 Pts",
          scoring_bodyguard_sacrifice:
            "• Bodyguard Sacrifice: +15 Pts (when dying to protect target)",
          scoring_cupid_failure: "• Cupid Failure (both lovers die): -5 Pts",
          scoring_friendly_fire:
            "• Friendly Fire (Accidentally killing an ally): -10 Pts",
          scoring_doctor_heal: "• Successful Doctor Protection: +25 Pts when saving an actually attacked player",
          scoring_hunter_shot:
            "• Monster Hunter Dying Shot (hitting Mafia/Killer): +10 Pts",
          scoring_colonel_lead: "• Colonel Successful Vote Leadership: +15 Pts",
          scoring_mafia_standard_kill:
            "• Kill Standard Citizen / Cupid / Guard: +5 Pts",
          scoring_joker_win: "• Jester victory (executed by vote): +50 Pts",
          scoring_bomber_detonate: "• Rebel Bomber Detonation: +10 Pts",
          scoring_cupid_survival: "• Cupid Lovers Surviving: +10 Pts",
          scoring_bomber_penalty: "• Vote Against Rebel Bomber: -5 Pts",
          scoring_innocent_penalty: "• Vote to Execute Innocent Knight: -5 Pts",
          playerRange: "🛡️ 6 to 16 players",
          offlineMode: "⚡ 100% Offline",
          roleCount: "🎭 16 Royal Roles",
          nextNight: "Continue to the next night 🌙",
          sampleNames: "Sample names",
          playerPlaceholder: "Knight / player name...",
          roleSetupNote:
            "Select roles to match the exact number of registered players.",
          presetTitle: "⚡ Balanced Presets",
          preset6: "🛡️ 6-player setup (Beginner)",
          preset8: "⚔️ 8-player setup (Classic)",
          preset10: "👑 10-player setup (Epic)",
          preset12: "🔥 12-player setup (Chaos)",
          cancel: "Cancel",
          encyclopediaTitle: "📖 Medieval Roles Encyclopedia",
          conflictEnd: "The Royal Conflict Ends",
          rolesRecord: "All players' identities:",
          restartSame: "Play again with the same setup ⚔️",
          home: "Return to Main Menu 🏰",
          specialConfirm: "Carry Out Revenge 🏹",
          specialDefaultTitle: "The Hunter's Revenge!",
          specialDefaultDesc:
            "The Hunter has fallen and may fire one final shot at any player!",
          investigationTitle: "Imperial Investigation Result",
          inspectedIdentity: "Inspected knight's identity",
          investigationStatus: "Investigation result",
          investigationContinue: "Understood / Finish turn ✓",
          playerRole: "Player: {name}",
          votePrompt: "Knight {name}, choose who you accuse of treason:",
          targetPrefix: "⚔️ Target: ",
          protectPrefix: "🛡️ Protect: ",
          doctorSelfHealUsed: "Self-protection already used",
          doctorSelfHealNote: "*(You can heal yourself only once during the game, and you have already used it.)*",
          mafiaPartners: "Your mafia partners: {names}",
          godfatherMafia: "Mafia members under your command: {names}",
          soloMafia: "You are the only mafia member in this game",
          passVotingPhone: "Pass the phone discreetly to knight: {name}",
          readyToVote: "I am {name} - ready to vote",
          investigatePrefix: "🔍 Investigate: ",
          slasherPrompt: "Slasher, choose your independent victim tonight:",
          bodyguardPrompt:
            "Choose a knight to guard with your life (you die instead if they are attacked):",
          doctorPrompt:
            "Choose a knight to protect tonight (you may protect yourself):",
          investigatorPrompt:
            "Choose a knight to investigate their identity and allegiance:",
          spyReveal: "Your intelligence reveals:",
          mafiaMove: "The Mafia is moving to assassinate: [{name}]",
          noMafiaMove: "No Mafia movement has been detected yet.",
          cupidPrompt:
            "First night only: choose two hearts to bind as lovers (if one dies, the other dies too):",
          chooseTwo: "Choose two players:",
          cupidDone:
            "You bound the lovers on the first night; there is no further action tonight.",
          witchPrompt: "Witch, you may use your special potions:",
          mafiaVictim: "Mafia victim tonight:",
          noVictim: "None",
          healVictim: "Save the victim with the healing potion ({status})",
          witchHealSection: "Healing - Healing potion ({status})",
          witchPoisonSection: "Poison - Deadly poison ({status})",
          witchAvailable: "available",
          witchUsed: "used",
          available: "available",
          used: "used",
          poisonPrompt: "Deadly poison potion ({status}):",
          poisonPrefix: "🧪 Poison: ",
          sniperPrompt:
            "You have one bullet for the entire game. Do you want to snipe someone tonight?",
          sniperSpent: "You have already used your royal bullet.",
          sniperPrefix: "🎯 Snipe: ",
          citizenPrompt:
            "Honest Citizen, camouflage requires your presence here for a few seconds. Tap a name to confuse anyone watching:",
          camouflagePrefix: "🛡️ Camouflage: ",
          mafiaInvestigation: "A traitorous Mafia member! 🗡️",
          townInvestigation: "An honest and innocent knight 🛡️",
          serialKillerInvestigation: "⚠️ This knight is the (Serial Killer) - dangerous neutral!",
          jesterInvestigation: "🃏 This knight is the (Jester) - neutral!",
          mafiaTeamInvestigation: "🗡️ This knight is a traitor! (belongs to the Mafia team)",
          innocentInvestigation: "🛡️ This knight is innocent! (belongs to the Knights)",
          abstainPrompt: "Choose a target or press Skip / Abstain.",
          voteAgainst: "voted against",
          doubleWeight: "(double weight)",
          skipVoteTitle:
            "📜 The Council decided to skip and execute no one today.",
          skipVoteDesc:
            "Skip votes matched or exceeded the top suspect's votes. The next night will begin now.",
          skipVoteContinue: "Continue to night 🌙",
          tieTitle: "Council vote tie ⚖️",
          tieDesc:
            "The knights were evenly divided, so no suspect received a decisive majority; the session ends without an execution today.",
          jesterWin:
            "The Jester [{name}] wins! They fooled everyone into voting for their execution.",
          idiotTitle: "Royal pardon for the Idiot! 🥴",
          idiotDesc:
            "The council voted to execute [{name}], but their foolishness earned a pardon and removed their right to vote.",
          executionTitle: "Execution carried out: {name} ⚔️",
          executionDesc:
            "[{name}] fell to the executioner after receiving the most votes from the knights council.",
          loverDeath:
            "💔 [{name}] died of grief immediately after losing their lover!",
          hunterTitle: "🦅 The Hunter's final shot!",
          hunterDesc:
            "Hunter [{name}], before your final breath, choose a knight to take down with you:",
          hunterToast: "The Hunter fired and killed [{name}]!",
          kamikazeTitle: "💣 Rebel Kamikaze explosion!",
          kamikazeDesc:
            "You executed the Kamikaze [{name}]! Choose a knight to take with them:",
          kamikazeToast: "The Kamikaze exploded and killed [{name}]!",
          targetRequired: "Please choose a revenge target!",
          loverMorning:
            "💔 [{survivor}] could not survive the loss of their lover [{dead}] and died of grief.",
          timerEnded: "Discussion time is over! It is time to vote.",
          executionRole: "Executed player's true role:",
          voteDetails: "Vote breakdown:",
          noStats: "No saved statistics yet.",
          resetConfirm: "Are you sure you want to reset all points and data?",
          resetSuccess: "All points and data were reset successfully.",
          alive: "Alive",
          dead: "Dead",
          loverLabel: "(Lover)",
          bodyguardDeath:
            "⚔️ Bodyguard [{name}] died bravely while sacrificing themselves for their guard target.",
          mafiaDeath:
            "🗡️ Knight [{name}] was found dead in their room after a treacherous Mafia raid.",
          savedByProtection:
            "✨ Thanks to protection and medicine, a knight miraculously survived certain death tonight!",
          slasherDeath:
            "🪓 Knight [{name}] fell victim to a brutal crime by the serial killer.",
          sniperDeath:
            "🏹 The Royal Sniper's arrow pierced Knight [{name}] and killed them.",
          witchDeath:
            "🧪 Knight [{name}] died after drinking an unidentified poison.",
          townVictoryTitle: "⚔️ Honorable Knights victory! 🛡️",
          mafiaVictoryTitle: "🗡️ Traitor Mafia Knights victory! 💀",
          jesterVictoryTitle: "🃏 Brilliant Jester victory!",
          slasherVictoryTitle: "🪓 Lone Slasher victory!",
          loversVictoryTitle: "💘 Lovers victory!",
          loversVictoryDesc:
            "Lovers victory! The couple survived to the end and overcame the kingdom's conspiracies.",
          slasherVictoryDesc:
            "Lone Slasher victory! The killer eliminated almost everyone and stood alone above the ruins.",
          mafiaVictoryDesc:
            "Mafia and Shadow Knights victory! The Mafia seized control of the kingdom.",
          townVictoryDesc:
            "Knights and citizens victory! The kingdom was cleansed of traitors and killers.",
          roleStatus: "{name} {lover}{icon} {role} ({status})",
          livingKnights: "🛡️ Living Knights in Council",
          royalBulletin: "📜 Royal Morning Bulletin 📜",
          dayInKingdom: "Day",
          quietNight:
            "🕊️ A quiet and blessed night! The Kingdom woke up with no casualties among the Knights.",
          publicDiscussion: "⏳ Public Discussion Session",
          daylightActive: "Daylight Active",
          pause: "Pause ⏸️",
          resume: "Resume ▶️",
          reset: "Reset 🔄",
          addThirty: "+30s ⏱️",
          discussionNote:
            "Discuss and examine suspects before voting for execution at the gallows.",
          royalVote: "🗳️ Royal Elimination Vote",
          knightVote: "Knight's Vote",
          accuseExecute: "⚖️ Accuse & Execute:",
          skip: "Skip / Abstain",
          tieMessage:
            "⚖️ Vote Tie! A re-vote round will be held among the tied suspects.",
          roles: {
            mafia: [
              "Mafia (Traitor Knights)",
              "Mafia members wake each night to silently choose one victim.",
            ],
            citizen: [
              "Honest Citizen",
              "No special night powers. Their weapons are discussion, observation, and voting.",
            ],
            doctor: [
              "Plague Doctor",
              "Protects one player each night from a Mafia or killer attack.",
            ],
            investigator: [
              "Imperial Investigator",
              "Checks one player each night to discover their allegiance.",
            ],
            sniper: [
              "Royal Sniper",
              "Has one arrow for the entire game to shoot a suspect at night.",
            ],
            godfather: [
              "Godfather (Shadow Lord)",
              "Mafia leader who appears innocent to the investigator.",
            ],
            slasher: [
              "Lone Slasher",
              "An independent serial killer who seeks to stand alone at the end.",
            ],
            spy: [
              "Royal Spy",
              "Learns who the Mafia targeted without revealing their names.",
            ],
            jester: [
              "Jester (Joker)",
              "Tricks the town into executing them to win immediately!",
            ],
            colonel: [
              "Ruling Colonel",
              "A noble knight whose vote counts twice during the day.",
            ],
            kamikaze: [
              "Rebel Kamikaze",
              "When executed, detonates and takes one voter with them!",
            ],
            witch: [
              "Chemical Witch",
              "Has one healing potion and one poison potion.",
            ],
            bodyguard: [
              "Bodyguard",
              "Guards a player and sacrifices themselves if that player is attacked.",
            ],
            idiot: [
              "Village Idiot",
              "If executed, is pardoned but loses the right to vote.",
            ],
            hunter: [
              "Monster Hunter",
              "When killed, fires one final shot at a chosen player.",
            ],
            cupid: [
              "Cupid (Messenger of Lovers)",
              "On the first night, binds two hearts whose lives become linked.",
            ],
          },
        },
      };

window.dispatchEvent(new Event("translationsready"));