const ROLES_DATA = {
  mafia: {
    id: "mafia",
    name: "المافيا (الفرسان الخونة)",
    team: "mafia",
    teamName: "فريق المافيا",
    icon: "🗡️",
    image: "imges/card_mafia_v3.webp",
    desc: "يستيقظ أفراد المافيا كل ليلة لاختيار ضحية واحدة وتصفيتها بصمت.",
    nightOrder: 6,
    isUnique: false,
    defaultCount: 1,
  },
  citizen: {
    id: "citizen",
    name: "المواطن الشريف",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "🛡️",
    image: "imges/card_citizen_v3.webp",
    desc: "لا يملك قدرات ليلية خاصة. سلاحه هو النقاش، قوة الملاحظة، والتصويت النهاري.",
    nightOrder: 99,
    isUnique: false,
    defaultCount: 3,
  },
  doctor: {
    id: "doctor",
    name: "طبيب الطاعون",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "🩺",
    image: "imges/card_doctor_v3.webp",
    desc: "يختار لاعباً كل ليلة ليحميه ويشفيه من محاولة اغتيال المافيا أو السفاح.",
    nightOrder: 4,
    isUnique: true,
    defaultCount: 1,
  },
  investigator: {
    id: "investigator",
    name: "المحقق الإمبراطوري",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "🔍",
    image: "imges/card_investigator_v3.webp",
    desc: "يتحقق من هوية لاعب واحد كل ليلة ليكتشف إن كان ينتمي للمافيا أم بريء.",
    nightOrder: 3,
    isUnique: true,
    defaultCount: 1,
  },
  sniper: {
    id: "sniper",
    name: "القناص الملكي",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "🏹",
    image: "imges/card_sniper_v3.webp",
    desc: "يمتلك سهماً واحداً طوال اللعبة يمكنه إطلاقه ليلاً على أي مشتبه به.",
    nightOrder: 8,
    isUnique: true,
    defaultCount: 0,
  },
  godfather: {
    id: "godfather",
    name: "العراب (سيد الظلال)",
    team: "mafia",
    teamName: "فريق المافيا",
    icon: "👑",
    image: "imges/card_godfather_v3.webp",
    desc: 'زعيم المافيا. إذا فحصه المحقق ليلاً، تظهر نتيجته كـ "بريء ومواطن صالح" للتمويه.',
    nightOrder: 6,
    isUnique: true,
    defaultCount: 0,
  },
  slasher: {
    id: "slasher",
    name: "السفاح المنفرد",
    team: "neutral",
    teamName: "محايد منفرد",
    icon: "🪓",
    image: "imges/card_slasher_v3.webp",
    desc: "قاتل متسلسل مستقل يقتل لاعباً كل ليلة ويسعى للبقاء وحيداً بعد إبادة الجميع.",
    nightOrder: 7,
    isUnique: true,
    defaultCount: 0,
  },
  spy: {
    id: "spy",
    name: "الجاسوس الملكي",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "👁️",
    image: "imges/card_spy_v3.webp",
    desc: "يتجسس ليلاً لمعرفة من هو الشخص الذي استهدفته المافيا دون كشف أسمائهم.",
    nightOrder: 2,
    isUnique: true,
    defaultCount: 0,
  },
  jester: {
    id: "jester",
    name: "المهرج (الجوكر)",
    team: "neutral",
    teamName: "محايد منفرد",
    icon: "🃏",
    image: "imges/card_jester_v3.webp",
    desc: "هدفه الوحيد هو استفزاز الجميع وخداعهم للتصويت على إعدامه نهاراً ليفوز فوراً!",
    nightOrder: 99,
    isUnique: true,
    defaultCount: 0,
  },
  colonel: {
    id: "colonel",
    name: "العقيد الحاكم",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "🎖️",
    image: "imges/card_colonel_v3.webp",
    desc: "فارس نبيل صوته يعادل صوتين أثناء التصويت النهاري عند حدوث التعادل.",
    nightOrder: 99,
    isUnique: true,
    defaultCount: 0,
  },
  kamikaze: {
    id: "kamikaze",
    name: "الانتحاري المتمرد",
    team: "neutral",
    teamName: "محايد منفرد",
    icon: "💣",
    image: "imges/card_kamikaze_v3.webp",
    desc: "إذا صوّت المجلس على إعدامه نهاراً، يفجر نفسه فوراً ويأخذ أحد المصوتين معه!",
    nightOrder: 99,
    isUnique: true,
    defaultCount: 0,
  },
  witch: {
    id: "witch",
    name: "الساحرة الكيميائية",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "🧪",
    image: "imges/card_witch_v3.webp",
    desc: "تمتلك جرعة إحياء لإنقاذ ضحية الليل، وجرعة سم لقتل أي شخص (مرة واحدة لكل جرعة).",
    nightOrder: 9,
    isUnique: true,
    defaultCount: 0,
  },
  bodyguard: {
    id: "bodyguard",
    name: "الحارس الشخصي",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "🤺",
    image: "imges/card_bodyguard_v3.webp",
    desc: "يحرس لاعباً كل ليلة؛ وإذا هوجم ذلك اللاعب، يضحي الحارس بنفسه ويموت مكانه.",
    nightOrder: 5,
    isUnique: true,
    defaultCount: 0,
  },
  idiot: {
    id: "idiot",
    name: "المجنون الأبله",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "🥴",
    image: "imges/card_idiot_v3.webp",
    desc: "إذا صوت المجلس على إعدامه، يتم العفو عنه لجنونه ويبقى حياً لكن لا يحق له التصويت بعد ذلك.",
    nightOrder: 99,
    isUnique: true,
    defaultCount: 0,
  },
  hunter: {
    id: "hunter",
    name: "صياد الوحوش",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "🦅",
    image: "imges/card_hunter_v3.webp",
    desc: "عند موته أو إعدامه في أي وقت، يطلق طلقته الأخيرة ليقتل لاعباً يختاره فوراً.",
    nightOrder: 99,
    isUnique: true,
    defaultCount: 0,
  },
  cupid: {
    id: "cupid",
    name: "كيوبيد (الشبيك)",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "🪢",
    image: "imges/card_cupid_v3.webp",
    desc: "في الليلة الأولى فقط، يربط بين قلبين كمربوطين؛ فإذا مات أحدهما مات الآخر حسرة وكمداً!",
    nightOrder: 1,
    isUnique: true,
    defaultCount: 0,
  },
  mayor: {
    id: "mayor",
    name: "العمدة / قاضي القصر",
    team: "town",
    teamName: "فريق الفرسان",
    icon: "⚖️",
    image: "imges/card_mayor_v1.webp",
    desc: "فارس بلا مهمة ليلية. يكشف هويته نهاراً ليصبح صوته بثلاثة أصوات.",
    nightOrder: 99,
    isUnique: true,
    defaultCount: 0,
  },
  executioner: {
    id: "executioner",
    name: "الجلاد / صاحب الثأر",
    team: "neutral",
    teamName: "محايد منفرد",
    icon: "🪓",
    image: "imges/card_executioner_v1.webp",
    desc: "يفوز إذا أُقصي هدفه المحدد نهاراً، ويتحول إلى مهرج إذا مات الهدف ليلاً.",
    nightOrder: 99,
    isUnique: true,
    defaultCount: 0,
  },
  framer: {
    id: "framer",
    name: "المشعوذ / المحرّف",
    team: "mafia",
    teamName: "فريق المافيا",
    icon: "🧙",
    image: "imges/card_framer_v1.webp",
    desc: "يختار فارساً بريئاً ليظهر للمحقق كعضو في المافيا تلك الليلة.",
    nightOrder: 2,
    isUnique: true,
    defaultCount: 0,
  },
  copycat: {
    id: "copycat",
    name: "النسّاخ / المقلّد",
    team: "neutral",
    teamName: "محايد",
    icon: "🪞",
    image: "imges/card_copycat_v1.webp",
    desc: "يبدأ بلا قدرة، ثم يرث دور أول لاعب يموت وقدراته المتبقية.",
    nightOrder: 99,
    isUnique: true,
    defaultCount: 0,
  },
};